name: Build
env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
on: [push, pull_request]
jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v6
      - name: Build SDK
        run: xcodebuild -scheme VoiceIt3-IosSDK -destination 'platform=iOS Simulator,name=iPhone 16,OS=latest' build
      - name: Build Example
        run: |
          cd Example
          xcodebuild -project VoiceIt3Demo.xcodeproj -scheme VoiceIt3Demo -destination 'platform=iOS Simulator,name=iPhone 16,OS=latest' -resolvePackageDependencies
          xcodebuild -project VoiceIt3Demo.xcodeproj -scheme VoiceIt3Demo -destination 'platform=iOS Simulator,name=iPhone 16,OS=latest' build
